'use client'

import { NoteDTO } from '@/autogenerated/client/backend'
import { notesClient } from '@/clients/backend'
import { TrashBin } from '@gravity-ui/icons'
import { Button, Card } from '@heroui/react'
import { useRouter } from 'next/navigation'
import { useState } from 'react'

import { useFeedback } from '@/lib/feedback'
import { useDictionary, useLocale } from '@/lib/i18n/client'
import noteCardDictionary from './NoteCard.i18n'

export function NoteCard({ note }: { note: NoteDTO }) {
  const texts = useDictionary(noteCardDictionary)
  const locale = useLocale()
  const feedback = useFeedback()
  const router = useRouter()

  const [ state, setState ] = useState<'ready' | 'loading'>('ready')

  function onDelete() {
    setState('loading')

    notesClient()
      .deleteNote(note.id)
      .then(() => {
        feedback.success(texts.toastDeletedTitle)
        router.refresh()
      })
      .catch(() => feedback.danger(texts.toastDeleteFailedTitle, texts.toastDeleteFailedDescription))
      .finally(() => setState('ready'))
  }

  return (
    <Card>
      <Card.Header>
        <Card.Title>{ note.title }</Card.Title>
        <Card.Description>
          { texts.updated } { new Date(note.updatedAt).toLocaleString(locale, { dateStyle: 'medium', timeStyle: 'short' }) }
        </Card.Description>
      </Card.Header>
      {
        note.content &&
        <Card.Content className='whitespace-pre-line'>{ note.content }</Card.Content>
      }
      <Card.Footer className='flex justify-end'>
        <Button
          size='sm'
          variant='danger-soft'
          isPending={ state === 'loading' }
          onPress={ onDelete }>
          <TrashBin />
          { texts.buttonDelete }
        </Button>
      </Card.Footer>
    </Card>
  )
}
