package com.acme.server.domain.model.entity;

import java.util.UUID;

/**
 * Anything with an identity of its own. Identifiers are generated by the domain, never by the storage, so an entity is complete before it
 * is persisted.
 */
public interface Entity {

  static UUID generateId() {
    return UUID.randomUUID();
  }

  UUID getId();
}
