#!/usr/bin/env bash
# new-product.sh --target <dir> --name <Name> --slug <slug> --package <java.package> --domain <domain>
#                [--apps server,webapp,web]
#
# Creates a new product repository from this archetype: copies it (without git history, build
# output or dependencies), renames the placeholder identity, moves the Java sources to the new
# package, and makes a first commit. See .claude/skills/new-product/SKILL.md.
#
# Placeholders replaced, in this order:
#   com.acme (and its regex/path forms)  -> --package
#   acme.example                          -> --domain
#   ACME / Acme / acme                    -> SLUG / --name / --slug
set -euo pipefail

target='' name='' slug='' package='' domain='' apps='server,webapp,web'
while [ $# -gt 0 ]; do
  case "$1" in
    --target) target="$2"; shift 2 ;;
    --name) name="$2"; shift 2 ;;
    --slug) slug="$2"; shift 2 ;;
    --package) package="$2"; shift 2 ;;
    --domain) domain="$2"; shift 2 ;;
    --apps) apps="$2"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

for v in target name slug package domain; do
  [ -n "${!v}" ] || { echo "--$v is required" >&2; exit 2; }
done
[[ $slug =~ ^[a-z][a-z0-9]*$ ]] || { echo "--slug must match [a-z][a-z0-9]*" >&2; exit 2; }
[[ $package =~ ^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)*$ ]] || { echo "--package must be a lowercase Java package" >&2; exit 2; }
if [ -e "$target" ] && [ -n "$(ls -A "$target")" ]; then
  echo "$target exists and is not empty" >&2; exit 2
fi

source_dir="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$target"
target="$(cd "$target" && pwd)"

python3 - "$source_dir" "$target" "$name" "$slug" "$package" "$domain" "$apps" <<'PY'
import os, re, shutil, sys

src, dst, name, slug, package, domain, apps = sys.argv[1:]
apps = {a.strip() for a in apps.split(',') if a.strip()}
all_apps = {'server', 'webapp', 'web'}
unknown = apps - all_apps
if unknown:
    sys.exit(f'unknown apps: {", ".join(sorted(unknown))}')

SKIP_DIRS = {'.git', 'node_modules', '.next', 'target', '.source', 'autogenerated', '.screenshots',
             '.playwright-cli', '.cm', '.idea'}
# Archetype-only files: they scaffold products, they are not part of one.
SKIP_PATHS = {'scripts/new-product.sh', 'scripts/product-README.md', '.claude/skills/new-product'}
SKIP_PATHS |= {app for app in all_apps - apps}
TEXT_EXT = {'.java', '.xml', '.yml', '.yaml', '.json', '.md', '.mdx', '.ts', '.tsx', '.mts', '.mjs',
            '.js', '.css', '.sql', '.sh', '.properties', '.hcl', '.svg', '.env', '.mustache', '.txt'}
TEXT_NAMES = {'Dockerfile', '.gitignore', '.dockerignore', '.npmrc', '.nvmrc', 'project.env', '.env.example',
              'maven.config'}

pkg_path = package.replace('.', '/')
replacements = [
    ('com\\/acme', package.replace('.', '\\/')),   # Checkstyle suppressions (escaped path regex)
    ('com\\.acme', package.replace('.', '\\.')),   # Spotbugs filters (escaped package regex)
    ('com/acme', pkg_path),
    ('com.acme', package),
    ('acme.example', domain),
    ('ACME', slug.upper()),
    ('Acme', name),
    ('acme', slug),
]

def rewrite(text):
    for old, new in replacements:
        text = text.replace(old, new)
    return text

copied = changed = 0
for root, dirs, files in os.walk(src):
    rel_root = os.path.relpath(root, src)
    rel_root = '' if rel_root == '.' else rel_root
    dirs[:] = [d for d in dirs if d not in SKIP_DIRS
               and os.path.join(rel_root, d) not in SKIP_PATHS]
    if rel_root == os.path.join('web', 'public') and 'raw' in dirs:
        dirs.remove('raw')
    for f in files:
        rel = os.path.join(rel_root, f)
        if rel in SKIP_PATHS:
            continue
        out_rel = rel.replace('com/acme', pkg_path) if '/java/com/acme' in rel else rel
        out = os.path.join(dst, out_rel)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        ext = os.path.splitext(f)[1]
        if ext in TEXT_EXT or f in TEXT_NAMES:
            with open(os.path.join(root, f), encoding='utf-8') as fh:
                text = fh.read()
            new = rewrite(text)
            changed += new != text
            with open(out, 'w', encoding='utf-8') as fh:
                fh.write(new)
        else:
            shutil.copy2(os.path.join(root, f), out)
        copied += 1

# The product's README replaces the archetype's.
with open(os.path.join(src, 'scripts', 'product-README.md'), encoding='utf-8') as fh:
    readme = rewrite(fh.read())
with open(os.path.join(dst, 'README.md'), 'w', encoding='utf-8') as fh:
    fh.write(readme)

# Keep executables executable.
for root, _, files in os.walk(dst):
    for f in files:
        if f.endswith('.sh'):
            os.chmod(os.path.join(root, f), 0o755)

print(f'copied {copied} files, renamed the identity in {changed}')
print(f'apps: {", ".join(sorted(apps))}' + (f' (left out: {", ".join(sorted(all_apps - apps))})' if all_apps - apps else ''))
PY

cd "$target"
if [ ! -d .git ]; then
  git init -q -b main
  git add -A
  git -c user.name="${GIT_AUTHOR_NAME:-$(git config user.name || echo archetype)}" \
      -c user.email="${GIT_AUTHOR_EMAIL:-$(git config user.email || echo archetype@localhost)}" \
      commit -q -m "Scaffold $name from the archetype"
fi

remaining="$(grep -rIl --exclude-dir=.git -e 'acme' . | grep -v 'package-lock.json' || true)"
echo "created $target"
if [ -n "$remaining" ]; then
  echo 'still mentioning "acme" (review by hand):'
  echo "$remaining" | sed 's/^/  /'
fi
echo 'next: build every app (see .claude/skills/new-product/SKILL.md), push, then run /product-setup'
