import { Configuration, NotesApi } from '@/autogenerated/client/backend'
import { getAccessToken } from '@auth0/nextjs-auth0'
import axios, { AxiosInstance } from 'axios'
import axiosRetry, { isRetryableError } from 'axios-retry'

function configuration() {
  const configuration = new Configuration()
  configuration.basePath = process.env.NEXT_PUBLIC_API_ENDPOINT
  return configuration
}

// `token` is only known upfront on the server, where it comes from the session.
// Client components leave it `undefined` so it's fetched lazily, per request.
function instance(token?: string | null): AxiosInstance {
  const instance = axios.create()
  instance.interceptors.request.use(async (request) => {
    const accessToken = token !== undefined ? token : await getAccessToken()
    if (accessToken) {
      request.headers.Authorization = `Bearer ${accessToken}`
    }
    return request
  })

  axiosRetry(instance, {
    retries: 1,
    retryCondition: isRetryableError, // network error or a 5xx error
    onRetry: (count, error, requestConfig) => {
      console.error(`Request attempt failed! [attempt=${count}, url=${requestConfig.url}, error=${error}]`)
    }
  })

  return instance
}

// One factory per generated API (one per OpenAPI tag).
export const notesClient = (token?: string | null): NotesApi => new NotesApi(configuration(), undefined, instance(token))
