import { NoteDTO } from '@/autogenerated/client/backend'
import { notesClient } from '@/clients/backend'
import Error from '@/components/Error'
import { auth0 } from '@/lib/auth0'
import { Typography } from '@heroui/react'
import { AxiosError } from 'axios'
import { Metadata } from 'next'
import { NoteCard, NoteForm } from './_components'

import { getDictionary } from '@/lib/i18n/server'
import pageDictionary from './i18n'

type ErrorKey = keyof (typeof pageDictionary)['es']['errors']

export async function generateMetadata(): Promise<Metadata> {
  const texts = await getDictionary(pageDictionary)

  return {
    title: texts.metadataTitle,
    description: texts.metadataDescription,
  }
}

export default async function Page() {
  const texts = await getDictionary(pageDictionary)
  const { notes, error } = await getData()

  if (error) return <Error error={ texts.errors[error] } />

  return (
    <>
      <Typography type='h1'>{ texts.title }</Typography>
      <Typography type='body-sm' color='muted'>{ texts.description }</Typography>
      <div className='mt-6 grid gap-6 lg:grid-cols-[360px_1fr] items-start'>
        <NoteForm />
        <div className='grid gap-4 sm:grid-cols-2'>
          {
            notes?.length
              ? notes.map(note => <NoteCard key={ note.id } note={ note } />)
              : <Typography type='body-sm' color='muted'>{ texts.empty }</Typography>
          }
        </div>
      </div>
    </>
  )
}

async function getData(): Promise<{ notes?: NoteDTO[], error?: ErrorKey }> {
  try {
    const { token } = await auth0.getAccessToken()
    const response = await notesClient(token).findNotes(0, 20)

    return { notes: response.data.items }
  } catch (e) {
    if (e instanceof AxiosError) {
      console.error('Error fetching notes [code=' + e.response?.status + ']', e.response?.data)

      switch (e.response?.status) {
        case 401: return { error: 'unauthorized' }
        case 403: return { error: 'forbidden' }
      }
    } else {
      console.error('Unexpected error fetching notes', e)
    }
  }

  return { error: 'unknown' }
}
